version: "3"
services:
  hardhat:
    build: ./packages/hardhat
    restart: unless-stopped
    volumes:
      - ./:/code:cached
    ports:
      - "8545:8545" # Standard port for interacting with the blockchain

  react-app: # The frontend app
    build: ./packages/react-app
    restart: unless-stopped
    volumes:
      - ./:/code:cached
    ports:
      - "3000:3000"

  yarn: # the control node that runs yarn commands
    build: ./
    volumes:
      - ./:/code:cached