services:
  graph-node: # Provides a subgraph interface for the blockchain
    image: graphprotocol/graph-node:latest
    restart: unless-stopped
    depends_on:
      - ipfs
      - postgres
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "localhost:http://host.docker.internal:8545"
      GRAPH_LOG: info
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres: # Used to support the graphQL node
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    command: [ "postgres", "-cshared_preload_libraries=pg_stat_statements" ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  ipfs: # used for playing around and the graph node
    image: ipfs/kubo:latest
    restart: unless-stopped
    environment:
      IPFS_SWARM_KEY: ${SWARM_KEY}
      LIBP2P_FORCE_PNET: 1
    ports:
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
      - "4001:4001/tcp"
      - "4001:4001/udp"
    volumes:
      - ./data/ipfs:/data/ipfs:cached
